# Generated by Django 5.0.4 on 2024-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcmodel',
            name='a',
            field=models.FloatField(default=0, verbose_name='Ребро A'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='h',
            field=models.FloatField(default=0, verbose_name='Высота H'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='m',
            field=models.FloatField(default=0, verbose_name='Объём жидкости M'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='r',
            field=models.FloatField(default=0, verbose_name='Радиус основания R'),
        ),
    ]
