# Generated by Django 5.0.4 on 2024-05-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0004_abcmodel_result_alter_abcmodel_tusk'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
