# Generated by Django 5.0.4 on 2024-05-02 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0005_abcmodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания'),
        ),
    ]
